name: Bug report
description: Report a bug with the Stable Diffusion cpp integration
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Home Assistant logs
      render: text
  - type: input
    id: ha-version
    attributes:
      label: Home Assistant version
    validations:
      required: true
  - type: input
    id: integration-version
    attributes:
      label: Integration version
    validations:
      required: true
